from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class HSRoleSpec:
    optimize: bool
    source_fields: tuple[str, ...]
    target_fields: tuple[str, ...]
    exact_source_cap_fields: tuple[str, ...] = ()
    use_transition_supply_cap: bool = False
    pp_upper: float = 1.25
    pn_lower: float = 0.85
    pn_upper: float = 1.03
    np_lower: float = 0.85
    np_upper: float = 1.03
    pp_delta: float = 0.15
    pn_delta: float = 0.08
    np_delta: float = 0.08
    note: str = ""


# V3 only optimizes HS folders that come directly from UN Comtrade.
# Li_000000 is kept as baseline because it is a synthetic bucket rather than a true HS code.
HS_ROLE_CONFIG: dict[str, HSRoleSpec] = {
    "1st_post_trade/Li_253090": HSRoleSpec(
        optimize=True,
        source_fields=("mining_lithium_ores",),
        target_fields=("processing_lithium_ores_total",),
        exact_source_cap_fields=("mining_lithium_ores",),
        pp_upper=1.35,
        pn_lower=0.75,
        pn_upper=1.03,
        np_lower=0.75,
        np_upper=1.03,
        pp_delta=0.12,
        pn_delta=0.08,
        np_delta=0.08,
        note="Mixed-product family: allow wider movement because the code can contain non-target products.",
    ),
    "2nd_post_trade/Li_000000": HSRoleSpec(
        optimize=False,
        source_fields=(),
        target_fields=(),
        note="Synthetic bucket without a real HS code; keep baseline unchanged in V3.",
    ),
    "3rd_post_trade/Li_282520": HSRoleSpec(
        optimize=True,
        source_fields=("refining_hydroxide",),
        target_fields=("cathode_ncm", "cathode_nca"),
        exact_source_cap_fields=("refining_hydroxide",),
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "3rd_post_trade/Li_283691": HSRoleSpec(
        optimize=True,
        source_fields=("refining_carbonate",),
        target_fields=("cathode_lfp",),
        exact_source_cap_fields=("refining_carbonate",),
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "1st_post_trade/Ni_260400": HSRoleSpec(
        optimize=True,
        source_fields=("mining_concentrate",),
        target_fields=("processing_total",),
        exact_source_cap_fields=("mining_concentrate",),
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "2nd_post_trade/Ni_750110": HSRoleSpec(
        optimize=True,
        source_fields=("processing_battery",),
        target_fields=("refining_total",),
        use_transition_supply_cap=True,
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "2nd_post_trade/Ni_750120": HSRoleSpec(
        optimize=True,
        source_fields=("processing_battery",),
        target_fields=("refining_total",),
        use_transition_supply_cap=True,
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "2nd_post_trade/Ni_750300": HSRoleSpec(
        optimize=True,
        source_fields=("processing_battery",),
        target_fields=("refining_total",),
        use_transition_supply_cap=True,
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "2nd_post_trade/Ni_750400": HSRoleSpec(
        optimize=True,
        source_fields=("processing_battery",),
        target_fields=("refining_total",),
        use_transition_supply_cap=True,
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "3rd_post_trade/Ni_283324": HSRoleSpec(
        optimize=True,
        source_fields=("refining_total",),
        target_fields=("cathode_ncm", "cathode_nca"),
        exact_source_cap_fields=("refining_total",),
        pp_upper=1.20,
        pn_lower=0.86,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "1st_post_trade/Co_260500": HSRoleSpec(
        optimize=True,
        source_fields=("mining_concentrate",),
        target_fields=("processing_total",),
        exact_source_cap_fields=("mining_concentrate",),
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "2nd_post_trade/Co_282200": HSRoleSpec(
        optimize=True,
        source_fields=("processing_total",),
        target_fields=("refining_mid",),
        use_transition_supply_cap=True,
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "2nd_post_trade/Co_810520": HSRoleSpec(
        optimize=True,
        source_fields=("processing_total",),
        target_fields=("refining_mid",),
        use_transition_supply_cap=True,
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "2nd_post_trade/Co_810530": HSRoleSpec(
        optimize=True,
        source_fields=("processing_total",),
        target_fields=("refining_mid",),
        use_transition_supply_cap=True,
        pp_upper=1.20,
        pn_lower=0.88,
        pn_upper=1.03,
        np_lower=0.88,
        np_upper=1.03,
        pp_delta=0.08,
        pn_delta=0.05,
        np_delta=0.05,
        note="Target-dominant family: most trade should already be close to target product flow, so keep bounds tighter.",
    ),
    "3rd_post_trade/Co_283329": HSRoleSpec(
        optimize=True,
        source_fields=("refining_mid",),
        target_fields=("cathode_ncm", "cathode_nca"),
        exact_source_cap_fields=("refining_mid",),
        pp_upper=1.35,
        pn_lower=0.75,
        pn_upper=1.03,
        np_lower=0.75,
        np_upper=1.03,
        pp_delta=0.12,
        pn_delta=0.08,
        np_delta=0.08,
        note="Mixed-product family: allow wider movement because the code can contain non-target products.",
    ),
}

